# Generated by Django 5.2.17 on 2026-08-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_uid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Upwork's job identifier (the ~token in the job URL). The real dedupe key.",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("upwork_url", models.URLField(max_length=1000)),
                ("title", models.CharField(max_length=500)),
                (
                    "snippet_text",
                    models.TextField(
                        blank=True,
                        help_text="Short excerpt from the Gmail alert email — never the full job description.",
                    ),
                ),
                (
                    "extracted_description",
                    models.TextField(
                        blank=True,
                        help_text="Optionally populated from Claude's read of the screenshots at hook-generation time.",
                    ),
                ),
                (
                    "freelancer_type",
                    models.CharField(
                        choices=[
                            ("single", "Single freelancer"),
                            ("multiple", "Multiple freelancers"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                (
                    "classification_meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Matched keywords/rules from the classifier, for debugging.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewed", "Reviewed"),
                            ("screenshots_added", "Screenshots added"),
                            ("hooks_generated", "Hooks generated"),
                            ("proposal_ready", "Proposal ready"),
                            ("applied", "Applied"),
                            ("skipped", "Skipped"),
                        ],
                        default="new",
                        max_length=32,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
