# Generated by Django 5.2.17 on 2026-08-30 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreelancerTypeCorrection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_type",
                    models.CharField(
                        choices=[
                            ("single", "Single freelancer"),
                            ("multiple", "Multiple freelancers"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "corrected_type",
                    models.CharField(
                        choices=[
                            ("single", "Single freelancer"),
                            ("multiple", "Multiple freelancers"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text='Why this job is actually single/multiple — e.g. "mentions team of 3 testers". Mined for keywords the classifier learns from.',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freelancer_type_corrections",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearnedKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phrase", models.CharField(max_length=100)),
                (
                    "freelancer_type",
                    models.CharField(
                        choices=[
                            ("single", "Single freelancer"),
                            ("multiple", "Multiple freelancers"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Incremented each time a new correction reinforces this phrase.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-weight", "phrase"],
                "unique_together": {("phrase", "freelancer_type")},
            },
        ),
    ]
