# Generated by Django 5.2.17 on 2026-08-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_freelancertypecorrection_learnedkeyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_favorite",
            field=models.BooleanField(
                default=False,
                help_text="Starred jobs are also protected from the retention purge.",
            ),
        ),
    ]
