# Generated by Django 5.2.17 on 2026-08-29 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobScreenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="job_screenshots/%Y/%m/")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Reading order for multi-screenshot jobs."
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["job", "order", "uploaded_at"],
            },
        ),
    ]
